/*******************************************************************************
* intelhexclass - class definitions                                            *
*                                                                              *
* A class to handle the encoding and decoding of an Intel HEX format file as   *
* generated by many tool chains for embedded processors and microcontrollers.  *
*                                                                              *
* This class is constructed based upon the definition given in the document    *
* 'Hexadecimal Object File Format Specification', Revision A, January 6, 1988, *
* © 1998 Intel Corporation                                                     *
*------------------------------------------------------------------------------*
* class intelhex                                                               *
*   Member Functions:                                                          *
*                                                                              *
*******************************************************************************/
#include <iostream>
#include <map>

using namespace std;

class intelhex {
        /* Output stream operator to encode contents                          */
        friend ostream& operator<<(ostream& dataOut, 
                                   const intelhex& intelhexData);
        
        /* Input stream to decode contents                                    */
        friend istream& operator>>(istream& dataIn, 
                                   const intelhex& intelhexData);
                                   
        /* Converts ASCII char to their HEX values                            */
        friend unsigned char charToHex(char value);
        
        /* Converts a 2 char string to its HEX value                          */
        friend unsigned char stringToHex(string value);
        
        /* Convert the data content of a data record                          */
        friend void decodeDataRecord(unsigned char recordLength,
                                     string data);
        
    private:
        /* Stores the addresses and their data of the HEX file                */
        map<int, unsigned char> ihContent;
        
        /* Iterator for Intel HEX Content map                                 */
        map<int, unsigned char>::iterator ihIterator;
        
        /* Return value for handling results of map operations                */
        pair<map<int, unsigned char>::iterator,bool> ihReturn;
  
        /* Stores the segment base address                                    */
        unsigned long segmentBaseAddress;
        
        /* Stores the CS register value for a 'Start Segment Address Record'  */
        unsigned short csRegister;
        
        /* Stores the IP register value for a 'Start Segment Address Record'  */
        unsigned short ipRegister;
        
        /* Stores the EIP register value for a 'Start Linear Address Record'  */
        unsigned long eipRegister;
        
    public:
        /* Constructor                                                        */
        intelhex();

        /* Destructor                                                         */
        ~intelhex();
        
        unsigned long outputSBA();
};
    
