######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 7 10:14:01 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += ../intelhex_class/

# Input
SOURCES += ihIntegrity.cpp ../intelhex_class/intelhexclass.cpp
